import type { SectorId, SectorDefinition } from '../types';

export const SECTORS: Record<SectorId, SectorDefinition> = {
  technology: {
    nameKo: '기술',
    nameEn: 'Technology',
    etf: 'XLK',
    icon: 'Cpu',
    fxSensitivity: 'neutral',
    rateSensitivity: 'negative-high',
  },
  healthcare: {
    nameKo: '헬스케어',
    nameEn: 'Healthcare',
    etf: 'XLV',
    icon: 'HeartPulse',
    fxSensitivity: 'neutral',
    rateSensitivity: 'negative-low',
  },
  financials: {
    nameKo: '금융',
    nameEn: 'Financials',
    etf: 'XLF',
    icon: 'Landmark',
    fxSensitivity: 'neutral',
    rateSensitivity: 'positive-high',
  },
  energy: {
    nameKo: '에너지',
    nameEn: 'Energy',
    etf: 'XLE',
    icon: 'Zap',
    fxSensitivity: 'positive',
    rateSensitivity: 'negative-low',
  },
  'consumer-discretionary': {
    nameKo: '임의소비재',
    nameEn: 'Consumer Discretionary',
    etf: 'XLY',
    icon: 'ShoppingBag',
    fxSensitivity: 'neutral',
    rateSensitivity: 'negative-high',
  },
  'consumer-staples': {
    nameKo: '필수소비재',
    nameEn: 'Consumer Staples',
    etf: 'XLP',
    icon: 'ShoppingCart',
    fxSensitivity: 'neutral',
    rateSensitivity: 'negative-low',
  },
  industrials: {
    nameKo: '산업재',
    nameEn: 'Industrials',
    etf: 'XLI',
    icon: 'Factory',
    fxSensitivity: 'negative',
    rateSensitivity: 'negative-medium',
  },
  'real-estate': {
    nameKo: '부동산(REIT)',
    nameEn: 'Real Estate',
    etf: 'XLRE',
    icon: 'Building2',
    fxSensitivity: 'neutral',
    rateSensitivity: 'negative-high',
  },
  utilities: {
    nameKo: '유틸리티',
    nameEn: 'Utilities',
    etf: 'XLU',
    icon: 'Plug',
    fxSensitivity: 'neutral',
    rateSensitivity: 'negative-high',
  },
  materials: {
    nameKo: '소재',
    nameEn: 'Materials',
    etf: 'XLB',
    icon: 'Gem',
    fxSensitivity: 'negative',
    rateSensitivity: 'negative-medium',
  },
  'communication-services': {
    nameKo: '커뮤니케이션',
    nameEn: 'Communication Services',
    etf: 'XLC',
    icon: 'Radio',
    fxSensitivity: 'neutral',
    rateSensitivity: 'negative-medium',
  },
};

export const SECTOR_IDS = Object.keys(SECTORS) as SectorId[];
